/home/devel/pshell/shell.c:30:10: fatal error: encode_decode.h: No such file or directory    30 | #include "encode_decode.h"       |          ^~~~~~~~~~~~~~~~~ compilation terminated. make[2]: *** [CMakeFiles/pshell.dir/build.make:76: CMakeFiles/pshell.dir/shell.c.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:1998: CMakeFiles/pshell.dir/all] Error 2 make: *** [Makefile:91: all] Error 2
devel@pi5-70:~/master-repos/pshell $ diff encode_decode.h ../dwtlift-pi/encode_decode/encode_decode.h
This was added many builds and will require a change to compare.sh